modLoader = "javafml" #mandatory
loaderVersion = "${neo_loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "${issue_tracker_url}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "${logo_file}"
credits="${mod_credits}"
authors = "${mod_authors}"

description = "${mod_description}"

#Minecraft dependency
[[dependencies.${mod_id}]]
modId = "minecraft"
type = 'required'
versionRange = "[${minimum_minecraft_version},)"
ordering = "NONE"
side = "CLIENT"

#Mixins
[[mixins]]
config="${mod_id}-common.mixins.json"
